INSERT INTO recipes (
  title,
  category,
  photo,
  description,
  ingredients,
  instructions,
  servings,
  rating,
  cooking_time_minutes
) VALUES
(
  'Classic Pancakes',
  'Breakfast',
  'https://www.allrecipes.com/thmb/nPYYrGakrCU0oxVs4o0dUFu-cP4=/0x512/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/21014-good-old-fashioned-pancakes-VAT-003-3x2-02-6b79447c2dfb4f3692f2db1e3f58d182.jpg',
  'Fluffy homemade pancakes.',
  ARRAY['Flour', 'Milk', 'Eggs', 'Sugar', 'Baking Powder'],
  'Mix ingredients, cook on pan until golden.',
  2,
  4.5,
  5
),
(
  'Avocado Toast',
  'Breakfast',
  'https://www.allrecipes.com/thmb/mJJPeaKKj61DZ4kc_jHHVI3kmG8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/AvocadoToastwithEggFranceC4x3-bb87e3bbf1944657b7db35f1383fabdb.jpg',
  'Creamy avocado spread on toasted bread.',
  ARRAY['Avocado', 'Bread', 'Salt', 'Pepper', 'Lemon Juice'],
  'Mash avocado, spread on toast, season to taste.',
  1,
  4.3,
  10
),
(
  'Oatmeal with Fruits',
  'Breakfast',
  'https://www.pcrm.org/sites/default/files/Oatmeal%20and%20Berries.jpg',
  'Warm oatmeal topped with fresh fruits.',
  ARRAY['Oats', 'Water', 'Banana', 'Berries', 'Honey'],
  'Cook oats, top with sliced fruits and honey.',
  2,
  5.0,
  15
),
(
  'Smoothie Bowl',
  'Breakfast',
  'https://minimalistbaker.com/wp-content/uploads/2016/07/The-PERFECT-5-minute-Smoothie-Bowl-Simple-ingredients-naturally-sweet-SO-healthy-vegan-glutenfree-smoothiebowl-recipe.jpg',
  'A refreshing smoothie topped with fruits and nuts.',
  ARRAY['Banana', 'Spinach', 'Almond Milk', 'Granola'],
  'Blend ingredients, pour into a bowl, and top.',
  1,
  4.7,
  10
),
(
  'Eggs Benedict',
  'Breakfast',
  'https://www.jocooks.com/wp-content/uploads/2020/08/eggs-benedict-1-13.jpg',
  'Poached eggs on English muffins with hollandaise.',
  ARRAY['Eggs', 'English Muffins', 'Ham', 'Hollandaise Sauce'],
  'Poach eggs, assemble on muffins, drizzle sauce.',
  2,
  4.5,
  20
),
(
  'Caesar Salad',
  'Lunch',
  'https://bakerbynature.com/wp-content/uploads/2025/01/Caesar-Salad-9.jpg',
  'A fresh salad with romaine lettuce and Caesar dressing.',
  ARRAY['Romaine Lettuce', 'Croutons', 'Parmesan Cheese', 'Caesar Dressing'],
  'Toss ingredients together and serve chilled.',
  2,
  4.7,
  15
),
(
  'Turkey Sandwich',
  'Lunch',
  'https://www.seriouseats.com/thmb/97w7oMXdTDMWCCuuDoGqiz5Rmv0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/20191010-leftover-turkey-reuben-sandwich-vicky-wasik-hero-a7f18588174f4a789d3430abf814ca38.jpg',
  'A hearty sandwich with turkey and veggies.',
  ARRAY['Turkey', 'Bread', 'Lettuce', 'Tomato', 'Mayonnaise'],
  'Layer ingredients between slices of bread.',
  1,
  4.0,
  10
),
(
  'Quinoa Bowl',
  'Lunch',
  'https://images.themodernproper.com/production/posts/2020/QuinoaBowl_4.jpg?w=800&q=82&auto=format&fit=crop&dm=1737605526&s=c617498b670834babd96fbdcd128e1b4',
  'Nutritious quinoa bowl with vegetables and dressing.',
  ARRAY['Quinoa', 'Chickpeas', 'Cucumber', 'Feta', 'Olive Oil'],
  'Cook quinoa, mix with other ingredients, drizzle dressing.',
  2,
  3.8,
  30
),
(
  'Tomato Soup',
  'Lunch',
  'https://www.allrecipes.com/thmb/qAepi_kEfeNzEjm4TtdMDHMeHnE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/277311spicy-fresh-tomato-soupFranceC4x3-56454ad082214f33960f62665fc8c169.jpg',
  'Warm, comforting tomato soup served with bread.',
  ARRAY['Tomatoes', 'Onion', 'Garlic', 'Basil', 'Cream'],
  'Cook tomatoes and veggies, blend until smooth.',
  4,
  4.1,
  25
),
(
  'Sushi Rolls',
  'Lunch',
  'https://www.allrecipes.com/thmb/P0zUzOzkJGTm9iDvMnzdZ1ua_T8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/19511smoked-salmon-sushi-rollfabeveryday4x3-159a22b4d3ac49fe9a146db94b53c930.jpg',
  'Delicious sushi rolls with fresh ingredients.',
  ARRAY['Sushi Rice', 'Nori', 'Fish', 'Vegetables', 'Soy Sauce'],
  'Roll ingredients in nori and slice.',
  6,
  5.0,
  40
),
(
  'Spaghetti Carbonar with Eggs',
  'Dinner',
  'https://www.allrecipes.com/thmb/CKRPG_da4wLz3j0pYv0e2jDdF6A=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/4499842-257380-AR-spaghetti-alla-carbonara-tradizionali-buckwheat-queen-4x3-eb4e48956fbd4277adcc3556e3bf6ecc.jpg',
  'A classic Italian pasta dish with a creamy sauce.',
  ARRAY['Spaghetti', 'Eggs', 'Parmesan Cheese', 'Pancetta', 'Black Pepper'],
  'Cook pasta, mix with eggs and cheese, add pancetta.',
  4,
  4.6,
  30
),
(
  'Grilled Salmon',
  'Dinner',
  'https://www.allrecipes.com/thmb/S9CtWJQki8yNesfmTPt8tCDl6uo=/0x512/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/ALR-12720-grilled-salmon-i-VAT-4x3-888cac0fb8a34f6fbde7bf836850cd1c.jpg',
  'Perfectly grilled salmon served with vegetables.',
  ARRAY['Salmon', 'Olive Oil', 'Lemon', 'Herbs', 'Salt'],
  'Marinate salmon, grill until cooked through.',
  2,
  4.4,
  25
),
(
  'Beef Stir-Fry',
  'Dinner',
  'https://www.allrecipes.com/thmb/InZbAAssBhhPBPPqVhexfaK6sA8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/M7014953_JD_11856-4x3-1-0d0cefed5bea4c4ba04bee3ff63c439a.jpg',
  'Quick and flavorful beef stir-fry with vegetables.',
  ARRAY['Beef', 'Bell Peppers', 'Broccoli', 'Soy Sauce', 'Garlic'],
  'Stir-fry beef and veggies in a hot pan.',
  4,
  4.3,
  20
),
(
  'Vegetable Curry',
  'Dinner',
  'https://www.allrecipes.com/thmb/djEkHAUHBflfrzoCLPeAbn0a0oc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/13982-quick-and-easy-vegetable-curry-VAT-001-4x3-6a77fe207b71496da15bee83b5db22f9.jpg',
  'A rich and aromatic vegetable curry.',
  ARRAY['Mixed Vegetables', 'Coconut Milk', 'Curry Paste', 'Rice'],
  'Cook vegetables in coconut milk with curry paste.',
  4,
  5.0,
  35
),
(
  'Chicken Tacos',
  'Dinner',
  'https://www.allrecipes.com/thmb/nEXud4i-ZmJQmW2B_X4BDay06ZI=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/217890-ranch-chicken-tacos-VAT-001-4x3-26519e4dc43242b0b5c4ae09178511c5.jpg',
  'Flavorful chicken tacos topped with fresh ingredients.',
  ARRAY['Chicken', 'Taco Shells', 'Lettuce', 'Tomato', 'Cheese'],
  'Cook chicken, fill taco shells, and top as desired.',
  3,
  4.2,
  15
),
(
  'Spaghetti Aglio e Olio',
  'Dinner',
  'https://www.allrecipes.com/thmb/s6u_2dpgcuj32sjyKJTzHUpXFk0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8829154-42004bab5a0343579fbae2b77a6af065.jpg',
  'Simple Italian pasta dish.',
  ARRAY['Spaghetti', 'Garlic', 'Olive Oil', 'Chili Flakes'],
  'Cook pasta, sauté garlic, mix together.',
  4,
  4.8,
  20
),
(
  'Garlic Butter Shrimp',
  'Dinner',
  'https://www.allrecipes.com/thmb/PYlStsLc33QunInprsqhqMZArU8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8707636-garlic-butter-shrimp-jojamada-4x3-1-276e02bf5b884c04b1bedb6e57e4d4bf.jpg',
  'Succulent shrimp tossed in garlic butter and herbs.',
  ARRAY['Shrimp', 'Garlic', 'Butter', 'Parsley', 'Lemon'],
  'Sauté garlic in butter, add shrimp until pink, finish with lemon and parsley.',
  2,
  4.7,
  15
),
(
  'Chicken Alfredo Pasta',
  'Dinner',
  'https://www.allrecipes.com/thmb/L6XHFLKIpyzz2iIJRRRKztpFyT8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/9203140-9ef5315609dc4c3bbbdfc0c539bf2c37.jpg',
  'Creamy Alfredo pasta with grilled chicken.',
  ARRAY['Pasta', 'Chicken Breast', 'Cream', 'Parmesan', 'Garlic'],
  'Cook pasta; grill chicken; make sauce with cream, garlic, parmesan; combine.',
  4,
  4.6,
  30
),
(
  'Beef Tacos',
  'Dinner',
  'https://www.allrecipes.com/thmb/0af4bstQ_7L_5-3WersLJb1V5A4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/5507683-d90260ef71a44e3988219f46e6d70591.jpg',
  'Spiced ground beef in soft tortillas with toppings.',
  ARRAY['Ground Beef', 'Taco Seasoning', 'Tortillas', 'Lettuce', 'Cheddar'],
  'Cook beef with seasoning; warm tortillas; assemble with toppings.',
  4,
  4.5,
  20
),
(
  'Vegetable Stir Fry',
  'Dinner',
  'https://www.allrecipes.com/thmb/RbLgplpltHlYKvYRd79vSzKvpbw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/987394-efe9cc2da3e843cbb82c5798daeebffc.jpg',
  'Colorful mixed vegetables in a savory stir-fry sauce.',
  ARRAY['Broccoli', 'Bell Pepper', 'Carrot', 'Soy Sauce', 'Garlic'],
  'Stir-fry vegetables on high heat; add sauce; cook until crisp-tender.',
  3,
  4.3,
  15
),
(
  'Salmon with Lemon Dill',
  'Dinner',
  'https://www.allrecipes.com/thmb/STYFM6TeywhEFliPi0_yHWoIwfM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/6637559-cedar-plank-grilled-salmon-with-garlic-lemon-and-dill-Mackenzie-Schieck-4x3-1-aa9c00cd2c20464aa76e87f4d9cc6336.jpg',
  'Oven-baked salmon with lemon and fresh dill.',
  ARRAY['Salmon Fillets', 'Lemon', 'Dill', 'Olive Oil', 'Salt'],
  'Season salmon, bake until flaky, finish with lemon and dill.',
  2,
  4.8,
  18
),
(
  'Eggplant Parmesan',
  'Dinner',
  'https://www.allrecipes.com/thmb/SYLFQEdUs77haviXqVKPstPfex4=/0x512/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/25321-eggplant-parmesan-ii-DDMFS-4x3-6d53ce79765b4c3d9f554d2a47e14d00.jpg',
  'Baked breaded eggplant layered with marinara and cheese.',
  ARRAY['Eggplant', 'Breadcrumbs', 'Marinara', 'Mozzarella', 'Parmesan'],
  'Bread and bake eggplant slices; layer with sauce and cheese; bake until bubbly.',
  4,
  4.4,
  50
),
(
  'Chicken Curry',
  'Dinner',
  'https://www.allrecipes.com/thmb/o9Cs2KkpzW7FXLAhEjLItDNrBzY=/0x512/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/46822-Indian-Chicken-Curry-PICS-Beauty-4x3-9535b806e7dc4f1da14f8ddb7a6367a4.jpg',
  'Comforting chicken curry with warm spices.',
  ARRAY['Chicken', 'Onion', 'Tomato', 'Curry Powder', 'Coconut Milk'],
  'Sauté aromatics, add spices, chicken and tomatoes; simmer with coconut milk.',
  4,
  4.6,
  40
),
(
  'Margherita Pizza',
  'Dinner',
  'https://www.allrecipes.com/thmb/w4qiT98TMy_bUouM5hkz0-IhPXs=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/PuffPastryMargheritaPizzafabeveryday-5ed9c908f84441e8b5cd3f0425ecef0d.jpg',
  'Classic pizza with tomato, basil, and mozzarella.',
  ARRAY['Pizza Dough', 'Tomato Sauce', 'Mozzarella', 'Basil', 'Olive Oil'],
  'Stretch dough, add sauce and cheese, bake until crust is golden; top with basil.',
  3,
  4.7,
  20
),
(
  'Beef Stroganoff',
  'Dinner',
  'https://www.allrecipes.com/thmb/wy6uuIhE7wHNwHNcvgd0bBZF4KM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/475838-639b6d9a460c4a5da1b3e1396a97ff13.jpg',
  'Creamy beef and mushroom sauce served over noodles.',
  ARRAY['Beef Strips', 'Mushrooms', 'Onion', 'Sour Cream', 'Egg Noodles'],
  'Sear beef, sauté mushrooms and onion, add sauce and sour cream; serve over noodles.',
  4,
  4.5,
  35
),
(
  'Stuffed Bell Peppers',
  'Dinner',
  'https://www.allrecipes.com/thmb/4Wse8o-YIFvkjyVfrNFPtLvPsIc=/0x512/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/AR-236359-beef-and-rice-stuffed-bell-peppers-DDMFS-4x3-beauty-dd9458de98884d4eb362354ee626d70e.jpg',
  'Bell peppers filled with rice, meat and cheese, baked to perfection.',
  ARRAY['Bell Peppers', 'Ground Beef', 'Rice', 'Tomato Sauce', 'Cheddar'],
  'Mix cooked rice and beef with sauce; fill peppers; top with cheese and bake.',
  6,
  4.4,
  60
),
(
  'Lemon Herb Chicken',
  'Dinner',
  'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F01%2F26%2FSimple-Lemon-Herb-Chicken-2000.jpg&q=60&c=sc&poi=auto&orient=true&h=512',
  'Roasted chicken breasts with lemon and herbs.',
  ARRAY['Chicken Breast', 'Lemon', 'Rosemary', 'Olive Oil', 'Garlic'],
  'Marinate chicken, roast until cooked through, serve with pan juices.',
  4,
  4.6,
  30
),
(
  'Shrimp Paella',
  'Dinner',
  'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2021%2F11%2F04%2Fimage-460.jpg&q=60&c=sc&poi=auto&orient=true&h=512',
  'Spanish rice with shrimp, saffron and vegetables.',
  ARRAY['Rice', 'Shrimp', 'Saffron', 'Bell Pepper', 'Peas'],
  'Sauté ingredients, add rice and stock with saffron, simmer until rice is done.',
  4,
  4.7,
  40
),
(
  'Pork Chops with Apples',
  'Dinner',
  'https://www.allrecipes.com/thmb/Ea7N1TLk4neLGBEcgJFTRzFG55A=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/4570368-applesauce-pork-chops-Gary-Lee-Gillmeister-4x3-1-38244a0ed7684dc396b8396f6aaa08cc.jpg',
  'Pan-seared pork chops with caramelized apples and onions.',
  ARRAY['Pork Chops', 'Apple', 'Onion', 'Butter', 'Thyme'],
  'Sear chops, sauté apples and onions in butter, combine and finish cooking.',
  4,
  4.3,
  25
),
(
  'Mushroom Risotto',
  'Dinner',
  'https://www.allrecipes.com/thmb/jS8MN9Wqt63jmihoTQ7yLc497M4=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/9416606-74723cfc8c8b4e378d804b292b598649.jpg',
  'Creamy arborio rice with sautéed mushrooms and parmesan.',
  ARRAY['Arborio Rice', 'Mushrooms', 'Parmesan', 'Onion', 'White Wine'],
  'Toast rice, gradually add stock stirring constantly, finish with mushrooms and parmesan.',
  4,
  4.6,
  35
),
(
  'Beef Bourguignon',
  'Dinner',
  'https://www.allrecipes.com/thmb/HKRuYbWzT5L1g-dGbQ28_q3fL1o=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Easy-Beef-Bourguignon-France-C-1x1-1-2000-d5cfe1fd2624463e9832662e9a004c7d.jpg',
  'Classic French beef stew braised in red wine.',
  ARRAY['Beef Chuck', 'Red Wine', 'Carrot', 'Onion', 'Mushroom'],
  'Brown beef, add wine and stock, simmer with vegetables until tender.',
  6,
  4.8,
  180
),
(
  'Chicken Fajitas',
  'Dinner',
  'https://www.allrecipes.com/thmb/UNZMCXRd1KMETWzWqlT8qL6MeIk=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/1005429-karens-slow-cooker-chicken-fajitas-Trusted-Brands-1x1-1-9408e6ffa66f408ebfff70c56c60c987.jpg',
  'Sizzling chicken strips with peppers and onions for fajitas.',
  ARRAY['Chicken', 'Bell Peppers', 'Onion', 'Tortillas', 'Fajita Seasoning'],
  'Sauté chicken and vegetables with seasoning; serve with warm tortillas.',
  4,
  4.5,
  20
),
(
  'Lentil Soup',
  'Dinner',
  'https://www.allrecipes.com/thmb/_bvtK6VQb8rV4whUErtdntFUOHs=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/13978-lentil-soup-DDMFS-4x3-edfa47fc6b234e6b8add24d44c036d43.jpg',
  'Hearty lentil soup with vegetables and herbs.',
  ARRAY['Lentils', 'Carrot', 'Celery', 'Onion', 'Vegetable Stock'],
  'Sauté vegetables, add lentils and stock, simmer until lentils are tender.',
  6,
  4.4,
  45
),
(
  'Teriyaki Salmon Bowl',
  'Dinner',
  'https://www.allrecipes.com/thmb/cV1gx2Pv4LQd3_Z7jtF0JpdEhKM=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/11871553_5-Ingrediuent-Salmon-Teriyaki-Bowls_Peyton-Beckwith_4x3-6eebd27af072474f9b2c2f49d6edf32c.jpg',
  'Glazed salmon served over rice with vegetables.',
  ARRAY['Salmon', 'Teriyaki Sauce', 'Rice', 'Broccoli', 'Sesame Seeds'],
  'Glaze salmon with teriyaki, bake or pan-sear; serve over rice with veggies.',
  2,
  4.7,
  25
),
(
  'Gnocchi with Pesto',
  'Dinner',
  'https://www.allrecipes.com/thmb/38YYoAdB6PMKYRoBQ5-4BP3SWPg=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/230326gnocchi-with-chicken-pesto-and-fresh-mozzarellaMyHotSouthernMEss4x3-c649f7aa19594eeaa10530ae688ff25b.jpg',
  'Potato gnocchi tossed in fresh basil pesto and cherry tomatoes.',
  ARRAY['Gnocchi', 'Basil', 'Pine Nuts', 'Parmesan', 'Cherry Tomatoes'],
  'Cook gnocchi, toss with pesto and tomatoes, serve warm.',
  3,
  4.4,
  15
),
(
  'BBQ Pulled Pork Sandwiches',
  'Dinner',
  'https://www.allrecipes.com/thmb/jkgY77k3lKZSUEoxZ6CPlOwia0g=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/2077235-19269344fce84242b4b76bc8e9cea73a.jpg',
  'Slow-cooked pulled pork tossed in BBQ sauce on buns.',
  ARRAY['Pork Shoulder', 'BBQ Sauce', 'Buns', 'Coleslaw', 'Onion'],
  'Slow cook pork until tender, shred, mix with BBQ sauce, serve on buns with slaw.',
  8,
  4.6,
  480
),
(
  'Thai Green Curry',
  'Dinner',
  'https://www.allrecipes.com/thmb/trbEa6VCDJ7lg_3SI9W7GNcKwcY=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/282096-instant-pot-thai-style-green-curry-chicken-3d431b4b188f4ba990b57d75f44942e3.jpg',
  'Fragrant green curry with vegetables and choice of protein.',
  ARRAY['Green Curry Paste', 'Coconut Milk', 'Chicken', 'Bamboo Shoots', 'Basil'],
  'Simmer curry paste in coconut milk, add chicken and vegetables, finish with basil.',
  4,
  4.6,
  30
),
(
  'Spinach and Feta Stuffed Chicken',
  'Dinner',
  'https://www.allrecipes.com/thmb/THf_cUCTwxGq1knutMHGSdLesPI=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8653824-feta-spinach-stuffed-chicken-breasts-ddmfs-hero-4x3-42432-cfa7ced044aa4f3d8eb860a3a451cee8.jpg',
  'Juicy chicken breast stuffed with spinach and feta cheese.',
  ARRAY['Chicken Breast', 'Spinach', 'Feta', 'Garlic', 'Olive Oil'],
  'Stuff chicken with spinach and feta, secure and bake until cooked through.',
  4,
  4.5,
  35
),
(
  'Shrimp Scampi Linguine',
  'Dinner',
  'https://www.allrecipes.com/thmb/OSeHp5Si1XLqSkRHkat9d24hBpg=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/6064240-0129e7ef59894373b14b604cad3e0b18.jpg',
  'Garlicky shrimp tossed with linguine in lemon-butter sauce.',
  ARRAY['Shrimp', 'Linguine', 'Garlic', 'Butter', 'Lemon'],
  'Sauté garlic in butter, cook shrimp briefly, toss with pasta and lemon.',
  4,
  4.7,
  20
),
(
  'Baked Ziti',
  'Dinner',
  'https://www.allrecipes.com/thmb/a3-nk6kH6_SeeEKATjw4A0kPbgQ=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/AR-JF-11758-Baked-Ziti-ddmfs-3x4-0630757a10b1492e85daab40662225b3.jpg',
  'Pasta baked with ricotta, tomato sauce and melted mozzarella.',
  ARRAY['Ziti', 'Ricotta', 'Tomato Sauce', 'Mozzarella', 'Parmesan'],
  'Mix pasta with ricotta and sauce, top with mozzarella, bake until bubbly.',
  6,
  4.5,
  40
),
(
  'Seared Tuna Steak',
  'Dinner',
  'https://www.allrecipes.com/thmb/MrACYlrnSsSmKs-z3UH6sfQigL4=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/160099-seared-ahi-tuna-steaks-DDMFS-4x3-26f4691e91bd434e9d96c1c601608cbc.jpg',
  'Quick seared tuna with sesame crust and soy dipping sauce.',
  ARRAY['Tuna Steak', 'Sesame Seeds', 'Soy Sauce', 'Ginger', 'Lime'],
  'Coat tuna with sesame, sear briefly each side, serve with soy-ginger sauce.',
  2,
  4.6,
  10
),
(
  'Creamy Tomato Basil Soup',
  'Dinner',
  'https://www.allrecipes.com/thmb/OxtmbaKCzZPc6iorz1ru5KKsaLw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/13113-rich-and-creamy-tomato-basil-soup-DDMFS-4x3-e7bc78ff4c6b4f999f9e178d97466e6f.jpg',
  'Smooth tomato soup finished with cream and fresh basil.',
  ARRAY['Tomatoes', 'Onion', 'Garlic', 'Cream', 'Basil'],
  'Cook tomatoes with aromatics, blend until smooth, finish with cream and basil.',
  4,
  4.3,
  35
),
(
  'Vegetarian Chili',
  'Dinner',
  'https://www.allrecipes.com/thmb/jEWoP9Aj_RIPC_wSuB76_av_6-0=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/6281236-insanely-easy-vegetarian-chili-Ellyx3-1x1-1-d3b032efeb244cdc9b07c21a1f7943bb.jpg',
  'Hearty chili with beans, vegetables and spices.',
  ARRAY['Beans', 'Tomato', 'Bell Pepper', 'Onion', 'Chili Powder'],
  'Sauté vegetables, add beans and tomatoes, simmer with spices until flavors meld.',
  6,
  4.4,
  60
),
(
  'Steak with Chimichurri',
  'Dinner',
  'https://www.allrecipes.com/thmb/415ErxS1JKZ_752BPcV4Svr_w4E=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/3457367-b0264a5d3d3d480490a3921ea72f9157.jpg',
  'Grilled steak served with vibrant chimichurri sauce.',
  ARRAY['Steak', 'Parsley', 'Garlic', 'Olive Oil', 'Red Wine Vinegar'],
  'Grill steak to desired doneness; blend chimichurri ingredients and spoon over steak.',
  2,
  4.8,
  20
),
(
  'Butternut Squash Pasta',
  'Dinner',
  'https://www.allrecipes.com/thmb/ID97BJ8_Gta9otEhBKzz8xmbaH8=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/710152-728c3d5dc24649fcb65155381f7c59f7.jpg',
  'Roasted squash blended into a creamy pasta sauce with sage.',
  ARRAY['Butternut Squash', 'Pasta', 'Sage', 'Parmesan', 'Cream'],
  'Roast squash, blend into sauce, toss with pasta and garnish with sage and parmesan.',
  4,
  4.5,
  40
),
(
  'Fish Tacos',
  'Dinner',
  'https://www.allrecipes.com/thmb/ov4ijlOz9P9ogjtVL-dTWH5uimk=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/5390580-0953affd3c8b42c0aea28254dcbf72dd.jpg',
  'Crisp-fried or grilled fish in tortillas with slaw and lime.',
  ARRAY['White Fish', 'Tortillas', 'Cabbage', 'Lime', 'Sour Cream'],
  'Cook fish, warm tortillas, assemble with slaw, crema and lime.',
  4,
  4.6,
  25
),
(
  'Ratatouille',
  'Dinner',
  'https://www.allrecipes.com/thmb/PkW1sTYjqFy3NqU6DIPG-Ot2_0k=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/222006-disneys-ratatouille-DDMFS-4x3-36eb15843ab548a79e7aab761dac92e1.jpg',
  'Layered baked vegetables in a savory tomato base.',
  ARRAY['Zucchini', 'Eggplant', 'Tomato', 'Bell Pepper', 'Herbs de Provence'],
  'Sauté base sauce, layer sliced vegetables, bake until tender.',
  4,
  4.2,
  60
),
(
  'Korean Beef Bibimbap',
  'Dinner',
  'https://www.allrecipes.com/thmb/Ek7F_I3DXkxRUhijF8_74rOiVnc=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/228240-BibimbapKoreanRiceWithMixedVegtables-ddmfs-1X1-0668-4a27ecc75afd40c78baa24e4e75d65a6.jpg',
  'Mixed rice bowl with seasoned beef, vegetables and gochujang sauce.',
  ARRAY['Rice', 'Ground Beef', 'Spinach', 'Carrot', 'Gochujang'],
  'Cook rice; sauté beef with seasoning; assemble with vegetables and sauce; top with fried egg.',
  4,
  4.7,
  30
),
(
  'Chicken Marsala',
  'Dinner',
  'https://www.allrecipes.com/thmb/zNNDv5g6-eMcw4sH8Y3WAy4ePLk=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/5694215-easier-chicken-marsala-Allison-Volosin-4x3-1-bbd980b9d0a843ba9248613448c9d62f.jpg',
  'Pan-fried chicken cutlets with marsala wine and mushrooms.',
  ARRAY['Chicken Cutlets', 'Marsala Wine', 'Mushrooms', 'Butter', 'Flour'],
  'Dredge and sauté chicken, add mushrooms and marsala sauce; reduce and serve.',
  4,
  4.5,
  30
),
(
  'Cajun Jambalaya',
  'Dinner',
  'https://www.allrecipes.com/thmb/cPHoaTbKmhpI_h8Ax3dXOEV8EO4=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/1448054-a87a23fb37984168873153cf96fbb37a.jpg',
  'Spicy rice dish with sausage, chicken and shrimp.',
  ARRAY['Rice', 'Andouille Sausage', 'Chicken', 'Shrimp', 'Cajun Seasoning'],
  'Sauté ingredients, add rice and stock, simmer until rice absorbs flavors.',
  6,
  4.6,
  50
),
(
  'Greek Moussaka',
  'Dinner',
  'https://www.allrecipes.com/thmb/VYlqph8Apang_oxNWFq3KTA7BZc=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/19644-moussaka-DDMFS-4x3-066ed4bc6ee14583a81e276020bb4ea7.jpg',
  'Layered eggplant and spiced meat topped with béchamel.',
  ARRAY['Eggplant', 'Ground Lamb', 'Tomato', 'Béchamel', 'Onion'],
  'Layer cooked eggplant and meat sauce, top with béchamel and bake until set.',
  8,
  4.5,
  90
),
(
  'Spaghetti Carbonara',
  'Dinner',
  'https://www.allrecipes.com/thmb/lhLxw6rwEMT1crUHXmm5edrwjA8=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/245775-spaghetti-alla-carbonara-the-traditional-italian-recipe-DDMFS-4x3-879c32ee3cfb463582e3e6230e311029.jpg',
  'Classic carbonara with eggs, pancetta and pecorino.',
  ARRAY['Spaghetti', 'Eggs', 'Pancetta', 'Pecorino', 'Black Pepper'],
  'Cook pasta; mix eggs and cheese; toss hot pasta with pancetta and egg mixture off heat.',
  4,
  4.7,
  20
),
(
  'Chicken Piccata',
  'Dinner',
  'https://www.allrecipes.com/thmb/zrVggtbsm__lkbXoQGWdwfYmYe8=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8696288-chicken-piccata-meatballs-recipe-Allrecipes-Magzine-JF_ALRSP25_4x3-47dca6e6b5814a27bc16be19adb16ca5.jpg',
  'Light chicken in lemon-caper sauce.',
  ARRAY['Chicken Breast', 'Capers', 'Lemon', 'Butter', 'Flour'],
  'Pan-fry chicken, deglaze with lemon and stock, add capers and butter to finish.',
  4,
  4.5,
  25
),
(
  'Vegetable Lasagna',
  'Dinner',
  'https://www.allrecipes.com/thmb/XcxViM4UZeI7ZES68fxjiFmOPho=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/620560-8ffeed667b4144d3acd4b9e63d07c013.jpg',
  'Layered lasagna with roasted vegetables and cheese.',
  ARRAY['Lasagna Noodles', 'Zucchini', 'Spinach', 'Ricotta', 'Tomato Sauce'],
  'Assemble layers of noodles, vegetables, cheese and sauce; bake until bubbly.',
  8,
  4.4,
  60
),
(
  'Sausage and Peppers',
  'Dinner',
  'https://www.allrecipes.com/thmb/nEbW8dhrOnLxaNSORvu7hakKaDE=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/214500-sausage-peppers-onions-and-potato-bake-DDMFS-4x3-16e08956570d42578c49791529430d08.jpg',
  'Italian sausages simmered with peppers and onions in tomato sauce.',
  ARRAY['Italian Sausage', 'Bell Peppers', 'Onion', 'Tomato Sauce', 'Garlic'],
  'Brown sausages, sauté peppers and onions, combine with sauce and simmer.',
  4,
  4.3,
  30
),
(
  'Coconut Chickpea Curry',
  'Dinner',
  'https://www.allrecipes.com/thmb/VQjCXqH_01CQanJCyRPJRJdfnX8=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Coconut_Chickpea_Curry-4x3_039-cfa7a55e16434fba8641012f7b03cef8.jpg',
  'Creamy chickpea curry with coconut milk and spices.',
  ARRAY['Chickpeas', 'Coconut Milk', 'Onion', 'Curry Powder', 'Spinach'],
  'Sauté aromatics, add spices, chickpeas and coconut milk; simmer and add spinach.',
  4,
  4.4,
  30
),
(
  'Lamb Kofta',
  'Dinner',
  'https://www.allrecipes.com/thmb/SJs9olMhPlqCi8oGvvAJuxYrgxQ=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8645735_Spiced-Harissa-Beef-and-Lamb-Koftas_Dotdash-Meredith-Food-Studios_4x3-47c377b8eee34191bcda8a17ab3b927e.jpg',
  'Spiced lamb skewers served with yogurt sauce.',
  ARRAY['Ground Lamb', 'Cumin', 'Coriander', 'Garlic', 'Yogurt'],
  'Mix spices with lamb, form skewers, grill and serve with yogurt sauce.',
  4,
  4.6,
  25
),
(
  'Pad Thai',
  'Dinner',
  'https://www.allrecipes.com/thmb/2aHyh25LpKvT0N9Br-0H4hHjJTU=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/42968-pad-thai-DDMFS-4x3-f46b490ef89b4694b8bf4c5ac54a486b.jpg',
  'Stir-fried rice noodles with tamarind sauce, shrimp and peanuts.',
  ARRAY['Rice Noodles', 'Tamarind Paste', 'Shrimp', 'Egg', 'Peanuts'],
  'Soak noodles, stir-fry with sauce, shrimp, egg and garnish with peanuts.',
  4,
  4.7,
  25
),
(
  'Polenta with Mushroom Ragù',
  'Dinner',
  'https://www.allrecipes.com/thmb/8CfurqhEJin3lYkNUa8ZEY21oRM=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/AR-RM-234933-how-to-make-perfect-polenta-ddmfs-3x4-5d4dc27b993a4c4bb33db0e1163dbbba.jpg',
  'Creamy polenta topped with rich mushroom ragù.',
  ARRAY['Polenta', 'Mushrooms', 'Tomato', 'Onion', 'Parmesan'],
  'Cook polenta until creamy; simmer mushrooms in tomato sauce; spoon over polenta.',
  4,
  4.4,
  45
),
(
  'Shrimp and Grits',
  'Dinner',
  'https://www.allrecipes.com/thmb/iKqPEzusJ3xq_vXDDoBwzdqM_3c=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/1296334-e872b13b7f994296a78e0abc76bd3983.jpg',
  'Southern-style shrimp over cheesy grits with bacon.',
  ARRAY['Shrimp', 'Grits', 'Cheddar', 'Bacon', 'Butter'],
  'Cook grits with cheese, sauté shrimp with bacon and butter, serve together.',
  4,
  4.6,
  30
),
(
  'Chicken Enchiladas',
  'Dinner',
  'https://www.allrecipes.com/thmb/vJACQN2yolDHbVy4JCzFQYPnufU=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8691-chicken-enchiladas-DDMFS-4x3-322-de64088bd2e248c7b6f86572e821e9f7.jpg',
  'Shredded chicken rolled in tortillas topped with enchilada sauce and cheese.',
  ARRAY['Chicken', 'Tortillas', 'Enchilada Sauce', 'Cheddar', 'Onion'],
  'Fill tortillas with chicken, roll, top with sauce and cheese, bake until bubbly.',
  6,
  4.5,
  35
),
(
  'Pumpkin Curry',
  'Dinner',
  'https://www.allrecipes.com/thmb/JG2RVVqjFO_CLLEP5yI_TerlsnQ=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/4648542-6243d2b7e2654d129d463d80c760c82a.jpg',
  'Warm spiced pumpkin curry served with rice.',
  ARRAY['Pumpkin', 'Coconut Milk', 'Curry Powder', 'Onion', 'Spinach'],
  'Sauté aromatics, add pumpkin and coconut milk, simmer until tender and season.',
  4,
  4.2,
  35
),
(
  'Ginger Soy Chicken Thighs',
  'Dinner',
  'https://www.allrecipes.com/thmb/U2h66zzKQGxP0Y5OAv08IX4sO8U=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/6388915-478c6715817549378bfab4e272a9b3c6.jpg',
  'Sticky baked chicken thighs glazed with ginger-soy sauce.',
  ARRAY['Chicken Thighs', 'Soy Sauce', 'Ginger', 'Honey', 'Garlic'],
  'Marinate thighs, bake until glazed and cooked through.',
  4,
  4.6,
  40
),
(
  'Calamari Fra Diavolo',
  'Dinner',
  'https://www.allrecipes.com/thmb/bFDes_203bPq_GLihIzrXo_RqCM=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/1378041-calamari-with-tomato-sauce-ypiris-4x3-1-3c6787a7007749bbb53e7dc803f99dfd.jpg',
  'Spicy tomato-based seafood pasta with tender calamari.',
  ARRAY['Calamari', 'Tomato', 'Red Pepper Flakes', 'Garlic', 'Pasta'],
  'Cook sauce with garlic and chili, add calamari and simmer briefly, toss with pasta.',
  4,
  4.3,
  25
),
(
  'Avocado Chicken Salad',
  'Dinner',
  'https://www.allrecipes.com/thmb/0DRzb6OYDJLuKZ7ynD_WGXWWZZ4=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/3709155-09d4fd0a758e47f0b124bd5469ef44b2.jpg',
  'Light chicken salad with creamy avocado and lime dressing.',
  ARRAY['Chicken', 'Avocado', 'Lime', 'Cilantro', 'Red Onion'],
  'Mix shredded chicken with diced avocado and dressing; chill and serve.',
  4,
  4.1,
  15
),
(
  'Oven-Baked Trout Almondine',
  'Dinner',
  'https://www.beyondthechickencoop.com/wp-content/uploads/2022/11/Trout-Almondine.jpg',
  'Delicate trout baked with buttery almonds and lemon.',
  ARRAY['Trout', 'Almonds', 'Butter', 'Lemon', 'Parsley'],
  'Top trout with almonds and butter, bake until flaky, finish with lemon and parsley.',
  2,
  4.5,
  20
),
(
  'Mango Chicken Stir Fry',
  'Dinner',
  'https://www.allrecipes.com/thmb/6zs526myOl2zBhz-ll11RwB8hsM=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8527054-Mango-Chicken-Stir-Fry-Bibi8527057-1x1-1-6f6a16007da64afba20ce0c42d1e2a94.jpg',
  'Sweet and savory stir-fry with mango and chicken.',
  ARRAY['Chicken', 'Mango', 'Bell Pepper', 'Soy Sauce', 'Ginger'],
  'Stir-fry chicken and vegetables, add mango and sauce, cook until glazed.',
  4,
  4.3,
  20
),
(
  'Greek Yogurt Parfait',
  'Breakfast',
  'https://www.allrecipes.com/thmb/UjQ1j_qWbDFIMayS1WS507YZOxQ=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-1249377035-e5191d85528b48278b8ccef103207909.jpg',
  'Layers of Greek yogurt, granola and fresh berries.',
  ARRAY['Greek Yogurt', 'Granola', 'Strawberries', 'Blueberries', 'Honey'],
  'Layer yogurt, granola and berries; drizzle with honey.',
  1,
  4.5,
  5
),
(
  'Fluffy Banana Pancakes',
  'Breakfast',
  'https://www.allrecipes.com/thmb/iTFhAMfs0hCdtOy-U6paSu8DRc0=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/2143962-no-milk-no-wheat-banana-pancakes-Christina-4x3-1-7cc83181438844a7996ba5ebc6e60d1e.jpg',
  'Fluffy pancakes made with oats and ripe bananas.',
  ARRAY['Oats', 'Banana', 'Egg', 'Baking Powder', 'Milk'],
  'Blend ingredients, cook batter on skillet until golden on both sides.',
  2,
  4.3,
  15
),
(
  'Smoked Salmon Bagel',
  'Breakfast',
  'https://www.allrecipes.com/thmb/WQy0dxlVw4eStHnIDZJ7AjOFyRA=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8-5-Ingredient-Breakfast-Sandwiches-hero-01-1x1-1-381a5d9284bb4f3cbaa0908505229e74.jpg',
  'Toasted bagel with cream cheese, smoked salmon and capers.',
  ARRAY['Bagel', 'Cream Cheese', 'Smoked Salmon', 'Capers', 'Red Onion'],
  'Toast bagel, spread cream cheese, top with salmon, onion and capers.',
  1,
  4.6,
  8
),
(
  'Veggie Omelette',
  'Breakfast',
  'https://www.allrecipes.com/thmb/T3nAx6b5A-boO7qkDSojcbZ_DZ8=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/5658630-2000-74c9ee97036749fdbba7996ae77432a1.jpg',
  'Three-egg omelette filled with sautéed vegetables and cheese.',
  ARRAY['Eggs', 'Bell Pepper', 'Onion', 'Spinach', 'Cheddar'],
  'Sauté vegetables, pour beaten eggs, cook and fold with cheese.',
  1,
  4.4,
  10
),
(
  'Blueberry Muffins',
  'Breakfast',
  'https://www.allrecipes.com/thmb/Hc-WT1ton6x4_y3KW-bdCOKpaak=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/3206572-best-of-the-best-blueberry-muffins-footballgrl16-4x3-a2716a2580254c709a25cd4b05f1cd4a.jpg',
  'Moist homemade muffins studded with fresh blueberries.',
  ARRAY['Flour', 'Sugar', 'Egg', 'Milk', 'Blueberries'],
  'Mix batter, fold in blueberries, bake until a toothpick comes out clean.',
  12,
  4.5,
  25
),
(
  'Breakfast Burrito',
  'Breakfast',
  'https://www.allrecipes.com/thmb/62KP7AShS9_1uPWWvh8KPz2zSkg=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/214583-SouthwestBreakfastBurritos-ddmfs-3x4-8401-156c7c8d657a4a5d9f3f393146fdafc3.jpg',
  'Tortilla filled with scrambled eggs, sausage, cheese and salsa.',
  ARRAY['Tortilla', 'Eggs', 'Sausage', 'Cheddar', 'Salsa'],
  'Scramble eggs with sausage, fill tortilla with eggs and cheese, roll and serve with salsa.',
  1,
  4.4,
  12
),
(
  'Chia Seed Pudding',
  'Breakfast',
  'https://www.allrecipes.com/thmb/BkqdYzeeCruk2NybFt7rcBI_KAo=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/237680-chia-seed-pudding-DDMFS-130-4x3-beauty-849744985bd14f8bbc7cf0c10b53707c.jpg',
  'Creamy chia pudding soaked overnight with vanilla and fruit.',
  ARRAY['Chia Seeds', 'Milk', 'Vanilla', 'Maple Syrup', 'Berries'],
  'Mix chia with milk and flavorings, refrigerate overnight, top with fruit.',
  2,
  4.2,
  480
),
(
  'French Toast',
  'Breakfast',
  'https://www.allrecipes.com/thmb/0_k2klomgU3DiTpyclXYucHtVw0=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/ALR-recipe-100490-eggnog-french-toast-VAT-hero-01-4x3-fc5489065d584e5f98673dd931c927ee.jpg',
  'Bread soaked in egg mixture, fried until golden and topped with syrup.',
  ARRAY['Bread', 'Eggs', 'Milk', 'Cinnamon', 'Maple Syrup'],
  'Dip bread in egg-milk mixture, cook on skillet until golden, serve with syrup.',
  2,
  4.5,
  15
),
(
  'Steel-Cut Oats with Apples',
  'Breakfast',
  'https://www.allrecipes.com/thmb/qn0qRza4vmOxNFIIWCXCEizsKA0=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/5423107-d2b3774716c94111857194b074998718.jpg',
  'Warm steel-cut oats cooked with cinnamon apples and nuts.',
  ARRAY['Steel-Cut Oats', 'Apple', 'Cinnamon', 'Brown Sugar', 'Walnuts'],
  'Cook oats, sauté apples with cinnamon and sugar, combine and top with nuts.',
  2,
  4.3,
  30
),
(
  'Cinnamon Roll Overnight Casserole',
  'Breakfast',
  'https://www.allrecipes.com/thmb/DzNXdziLobXiTgtdmgqoU1iKA94=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/229276-easy-cinnamon-rolls-DDMFS-4x3-a225ddff4e7948e9b239557f14a9c05b.jpg',
  'Easy overnight cinnamon roll bake ready for the morning.',
  ARRAY['Cinnamon Roll Dough', 'Eggs', 'Milk', 'Brown Sugar', 'Butter'],
  'Combine torn dough with egg-milk mixture and brown sugar, refrigerate overnight, bake and glaze.',
  6,
  4.4,
  45
),
(
  'Smoked Salmon Scramble',
  'Breakfast',
  'https://www.allrecipes.com/thmb/a_3LBKtVyJ63ee_cFUSGTGNhGFA=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/11681159_Easy-Creamy-Crockpot-Chicken-Enchilada-Casserole_4x3-ba2d4fec943740c38e07b4341aec6fc6.jpg',
  'Creamy scrambled eggs folded with smoked salmon and chives.',
  ARRAY['Eggs', 'Smoked Salmon', 'Butter', 'Chives', 'Cream'],
  'Whisk eggs with cream, cook slowly in butter, fold in salmon and chives off heat.',
  2,
  4.6,
  8
),
(
  'Granola and Fruit Bowl',
  'Breakfast',
  'https://www.allrecipes.com/thmb/LDtbTGiLW7yhgVrWYjtA6a1Uwes=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/6491747-f73764b0545f424bacf70ee427736f2f.jpg',
  'Crunchy granola served over yogurt with seasonal fruit.',
  ARRAY['Granola', 'Yogurt', 'Mixed Fruit', 'Honey', 'Seeds'],
  'Assemble yogurt, granola and fruit in a bowl; drizzle with honey.',
  1,
  4.1,
  5
),
(
  'Ham and Cheese Croissant',
  'Breakfast',
  'https://www.allrecipes.com/thmb/5Bmt3aEIJVferPVzHX1rIpNITzE=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8534313_Ham-and-Cheese-Croissant-Casserole_lutzflcat_1x1-25be061b075340faa1ba13a8a68906ad.jpg',
  'Buttery croissant filled with ham and melted cheese.',
  ARRAY['Croissant', 'Ham', 'Swiss Cheese', 'Butter', 'Mustard'],
  'Slice croissant, fill with ham and cheese, warm until cheese melts.',
  1,
  4.3,
  10
),
(
  'Sweet Potato Breakfast Hash',
  'Breakfast',
  'https://www.allrecipes.com/thmb/j5199zB0NLt4QtvlyOQ_1BzndlM=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/233328-savory-sweet-potato-hash-DDMFS-114-4x3-821d561a77554020ade0e7bb164359ac.jpg',
  'Roasted sweet potatoes with peppers, onions and fried egg.',
  ARRAY['Sweet Potato', 'Bell Pepper', 'Onion', 'Egg', 'Paprika'],
  'Sauté sweet potato and vegetables until tender, top with fried egg.',
  2,
  4.4,
  25
),
(
  'Ricotta Toast with Honey',
  'Breakfast',
  'https://www.allrecipes.com/thmb/4_dm-PN_E8PBPApwSZH818upcsM=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/6906566-dbdbf45fb41a4fe4b6cb0da3f7207a89.jpg',
  'Toast topped with creamy ricotta, honey and toasted nuts.',
  ARRAY['Bread', 'Ricotta', 'Honey', 'Almonds', 'Lemon Zest'],
  'Toast bread, spread ricotta, drizzle honey, sprinkle nuts and lemon zest.',
  1,
  4.2,
  7
),
(
  'Spinach Feta Egg Muffins',
  'Breakfast',
  'https://www.allrecipes.com/thmb/xr8kFOoFN8S2xgxHKrlkHg20O5w=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/AR-278443--Easy-Breakfast-Egg-Muffins-gw-ddmfs-beauty-4x3-8de490e94dac4f9baa51c73e02b67a28.jpg',
  'Baked egg muffins with spinach and feta — great for meal prep.',
  ARRAY['Eggs', 'Spinach', 'Feta', 'Milk', 'Salt'],
  'Whisk eggs with milk, fold in spinach and feta, pour into muffin tin and bake.',
  6,
  4.3,
  20
),
(
  'Apple Almond Overnight Oats',
  'Breakfast',
  'https://www.allrecipes.com/thmb/oAENXJIHtkcW_aYUdJxMubJDmzE=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Dominican-Style-Oatmeal-5cd1e3674b364d2194bf37884b6fc7ea.jpg',
  'Overnight oats with diced apple, almond butter and cinnamon.',
  ARRAY['Rolled Oats', 'Milk', 'Apple', 'Almond Butter', 'Cinnamon'],
  'Combine ingredients, refrigerate overnight and serve chilled or warmed.',
  1,
  4.2,
  480
),
(
  'Chicken Caesar Wrap',
  'Lunch',
  'https://www.allrecipes.com/thmb/Sz8N_zd91TX5x6KzmMeADq9vf-c=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/ar-caesar-wrap-4x3-8ceae71172794df49230bbf38c14b125.jpg',
  'Grilled chicken, romaine, parmesan and Caesar dressing wrapped in a tortilla.',
  ARRAY['Tortilla', 'Chicken', 'Romaine', 'Parmesan', 'Caesar Dressing'],
  'Toss chicken and lettuce with dressing, place in tortilla, add parmesan and roll.',
  1,
  4.5,
  10
),
(
  'Caprese Sandwich',
  'Lunch',
  'https://www.allrecipes.com/thmb/39kXcEJWmFvZly0XlCdtLSRZkhA=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/9404276-dd14638598024df0b1dfe791b3d191c6.jpg',
  'Fresh mozzarella, tomato, basil and balsamic on crusty bread.',
  ARRAY['Bread', 'Mozzarella', 'Tomato', 'Basil', 'Balsamic Glaze'],
  'Layer mozzarella and tomato on bread, top with basil and drizzle with balsamic.',
  1,
  4.4,
  5
),
(
  'Tuna Niçoise Salad',
  'Lunch',
  'https://www.allrecipes.com/thmb/7bs0BI1gQVLdbp_rJjAhRJ5knPg=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/ALR-recipe-14239-salad-nicoise-hero-01-ddmfs-4x3-21eceb81fd1043888fffbada1e0acb9b.jpg',
  'Classic Niçoise with tuna, green beans, potatoes and hard-boiled eggs.',
  ARRAY['Tuna', 'Green Beans', 'Potatoes', 'Eggs', 'Olives'],
  'Arrange cooked potatoes, beans and eggs with tuna and olives; dress and serve.',
  2,
  4.6,
  25
),
(
  'Grilled Cheese and Tomato Soup',
  'Lunch',
  'https://www.allrecipes.com/thmb/UK46jW4QWWCotigJYDPRWDI58Cw=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/7370778TomatoSoupwithGrilledCheeseCroutonsConfessionsofaGroceryAddict4x3-32b9a646e35d460eae38817cc5e1ff1f.jpg',
  'Melty grilled cheese served with a comforting tomato soup.',
  ARRAY['Bread', 'Cheddar', 'Tomato', 'Onion', 'Cream'],
  'Grill cheese sandwiches; simmer tomatoes and aromatics, blend to make soup.',
  2,
  4.5,
  20
),
(
  'Quinoa Chickpea Salad',
  'Lunch',
  'https://www.allrecipes.com/thmb/M9Xpvx2nHoK0T5GDc9Os4A8rgdI=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/11689874_Steak-Chimichurri-Dense-Bean-Salad_Peyton-Beckwith_4x3-31203c84672c4044817621894f64c84d.jpg',
  'Protein-packed salad with quinoa, chickpeas, veggies and lemon vinaigrette.',
  ARRAY['Quinoa', 'Chickpeas', 'Cucumber', 'Tomato', 'Lemon'],
  'Cook quinoa, toss with chickpeas and vegetables, dress with lemon vinaigrette.',
  3,
  4.3,
  20
),
(
  'BBQ Chicken Salad',
  'Lunch',
  'https://www.allrecipes.com/thmb/1IV8psnruDlnTXqiVQz4859prgQ=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/102046883-BBQ-Chicken-Chopped-Salad-3-Photo-by-Meredith-fa87a8f751f44bd696c178c3de3e2c88.jpg',
  'Smoky BBQ chicken over mixed greens with corn and avocado.',
  ARRAY['Chicken', 'BBQ Sauce', 'Mixed Greens', 'Corn', 'Avocado'],
  'Toss grilled BBQ chicken with salad ingredients and a light dressing.',
  2,
  4.4,
  25
),
(
  'Turkey Avocado Club',
  'Lunch',
  'https://www.allrecipes.com/thmb/GFeMcLdvGGKPWwhAeJ_t_1Qn10g=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/club-sandwich-4x3-1785a83b913344edaaaeb6745b73d9a9.jpg',
  'Triple-decker with turkey, bacon, avocado, lettuce and tomato.',
  ARRAY['Bread', 'Turkey', 'Bacon', 'Avocado', 'Tomato'],
  'Layer ingredients between toasted bread slices and slice to serve.',
  1,
  4.5,
  10
),
(
  'Mediterranean Grain Bowl',
  'Lunch',
  'https://www.allrecipes.com/thmb/N2U1p3m8NNA4jkCCZb7ZutevcSw=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Mediterranean-Farro-Salad-by-SunnDaysNora-2000-a9fb52e8ee1f4c958afe41c03a2599f8.jpg',
  'Farro or couscous bowl with roasted veggies, hummus and olives.',
  ARRAY['Farro', 'Zucchini', 'Red Pepper', 'Hummus', 'Olives'],
  'Cook grain, roast vegetables, assemble bowl with hummus and olives.',
  2,
  4.3,
  30
),
(
  'BLT Sandwich',
  'Lunch',
  'https://www.allrecipes.com/thmb/MCS9zyxsoOK6MWEAiArxExvKT9o=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/AR-209578-blt-DDMFS-3x4-e1e67e3c348645ba85e304249fd43ff9.jpg',
  'Classic bacon, lettuce and tomato with mayo on toasted bread.',
  ARRAY['Bread', 'Bacon', 'Lettuce', 'Tomato', 'Mayonnaise'],
  'Toast bread, fry bacon, assemble sandwich with mayo, lettuce and tomato.',
  1,
  4.2,
  12
),
(
  'Soba Noodle Salad',
  'Lunch',
  'https://www.allrecipes.com/thmb/GHJoFDYj6tSCI_kgVF-nIHNDxF8=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/245993-soba-noodle-salad-with-chicken-ands-sesame-GOLDMAN-4x3-2550-0f54425c6f524efdb5d37edb1a525cc5.jpg',
  'Chilled soba with crunchy veggies and sesame-ginger dressing.',
  ARRAY['Soba Noodles', 'Cucumber', 'Carrot', 'Sesame Oil', 'Ginger'],
  'Cook and chill noodles; toss with vegetables and sesame-ginger dressing.',
  2,
  4.4,
  15
),
(
  'Egg Salad Sandwich',
  'Lunch',
  'https://www.allrecipes.com/thmb/yPMz6g1nlAqrkZzfn7eYjU8UDdY=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/9412221-ad890e172abf4b7c9ecb932da886a3a7.jpg',
  'Creamy egg salad seasoned with mustard and chives on whole grain bread.',
  ARRAY['Eggs', 'Mayonnaise', 'Mustard', 'Chives', 'Bread'],
  'Mix chopped boiled eggs with mayo, mustard and chives; spread on bread.',
  2,
  4.1,
  15
),
(
  'Falafel Pita',
  'Lunch',
  'https://www.allrecipes.com/thmb/RBGbKYviIR9dL3IeoUTWj99zoQ0=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/IMG_2069-2000-d23f180f09c54647a6a70f85e2cbb14c.jpg',
  'Crispy falafel balls tucked into pita with tahini and salad.',
  ARRAY['Chickpeas', 'Parsley', 'Garlic', 'Pita', 'Tahini'],
  'Form and fry/bake falafel, stuff into pita with salad and drizzle tahini.',
  2,
  4.5,
  30
),
(
  'Poke Bowl',
  'Lunch',
  'https://www.allrecipes.com/thmb/pBZM5qg-BsoRM9AoUQCX0yxI9W0=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/12870-ahi-tuna-poke-beauty1-4x3-dea05e5e824b4b1987f78202887da37a.jpg',
  'Marinated raw fish over rice with seaweed, cucumber and avocado.',
  ARRAY['Sushi Rice', 'Ahi Tuna', 'Soy', 'Avocado', 'Cucumber'],
  'Marinate tuna, assemble over rice with vegetables and sauces.',
  1,
  4.7,
  15
),
(
  'Grain and Roasted Veg Wrap',
  'Lunch',
  'https://www.thegardengrazer.com/wp-content/uploads/2023/02/roasted-vegetable-wrap-75.jpg',
  'Hearty wrap with roasted seasonal vegetables, goat cheese and greens.',
  ARRAY['Wrap', 'Roasted Veggies', 'Goat Cheese', 'Spinach', 'Balsamic'],
  'Spread cheese on wrap, add roasted veggies and greens, drizzle balsamic and roll.',
  1,
  4.2,
  20
),
(
  'Chicken Parmesan Sub',
  'Lunch',
  'https://www.allrecipes.com/thmb/YMTqEW6aleXLQ5qCSNriJNi497A=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/7086525-7e47fd674b0343e69f3fa00543d2322b.jpg',
  'Breaded chicken, marinara and melted mozzarella on a toasted sub roll.',
  ARRAY['Sub Roll', 'Chicken Cutlet', 'Marinara', 'Mozzarella', 'Parmesan'],
  'Assemble fried/baked cutlet with sauce and cheese on roll, toast until melted.',
  1,
  4.6,
  25
),
(
  'Warm Lentil Salad',
  'Lunch',
  'https://www.allrecipes.com/thmb/SIWOoY7-1yu2OaIQJTDLeQtDGtU=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/267261-instant-pot-lentil-and-ham-soup-2000-21393d5ce29d4f53a81094891b2bb7e5.jpg',
  'Earthy lentils tossed with roasted carrots, feta and mustard vinaigrette.',
  ARRAY['Lentils', 'Carrot', 'Feta', 'Mustard', 'Olive Oil'],
  'Cook lentils, roast carrots, combine with feta and warm vinaigrette.',
  3,
  4.3,
  35
),
(
  'Grilled Veggie Panini',
  'Lunch',
  'https://www.allrecipes.com/thmb/Eprt3Ox8y94Ynq4n1741VAxmRGc=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Steak20and20Cheese20Panini20Photo20by20Meredith20650x465-38719295352344d3b04bd2a5218bcf83.jpg',
  'Pressed panini with grilled zucchini, peppers, pesto and provolone.',
  ARRAY['Ciabatta', 'Zucchini', 'Bell Pepper', 'Pesto', 'Provolone'],
  'Assemble sandwich with grilled vegetables and cheese, press until golden.',
  1,
  4.4,
  10
),
(
  'Cobb Salad',
  'Lunch',
  'https://www.allrecipes.com/thmb/cKFHtVWGrla7PWt8XRMIiJ_RJfQ=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/14415-cobb-salad-DDMFS-4x3-608ba9c5768b49079eb75fe9a9898307.jpg',
  'Classic Cobb with chicken, bacon, egg, avocado and blue cheese.',
  ARRAY['Chicken', 'Bacon', 'Egg', 'Avocado', 'Blue Cheese'],
  'Arrange ingredients over greens and serve with dressing.',
  2,
  4.6,
  20
),
(
  'Pasta Primavera',
  'Lunch',
  'https://www.allrecipes.com/thmb/ubrvFg7uelW9KyTdYJqvHgTMlQU=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/1104151-552577daf8404b8b9b7e124dd41c160a.jpg',
  'Light pasta tossed with seasonal vegetables and olive oil-garlic sauce.',
  ARRAY['Pasta', 'Broccoli', 'Peas', 'Parmesan', 'Garlic'],
  'Cook pasta, sauté vegetables, toss together with olive oil, garlic and parmesan.',
  3,
  4.3,
  25
),
(
  'Curry Chicken Salad',
  'Lunch',
  'https://www.allrecipes.com/thmb/jKRcGWhxQsDxdQ6yEf90RWOeLnY=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/58494-6bf049668d5a45adb5c2b89f52940331.jpg',
  'Curried chicken salad with grapes and almonds served on croissant or greens.',
  ARRAY['Chicken', 'Mayonnaise', 'Curry Powder', 'Grapes', 'Almonds'],
  'Mix shredded chicken with mayo, curry, grapes and almonds; serve chilled.',
  4,
  4.2,
  15
);
