INSERT INTO recipes (
  title,
  category,
  photo,
  description,
  ingredients,
  instructions,
  servings,
  rating,
  cooking_time_minutes
) VALUES
(
  'Classic Pancakes',
  'Breakfast',
  'https://images.unsplash.com/photo-1587738347113-1d8c36a2db9b',
  'Fluffy homemade pancakes.',
  ARRAY['Flour', 'Milk', 'Eggs', 'Sugar', 'Baking Powder'],
  'Mix ingredients, cook on pan until golden.',
  2,
  4.5,
  5
),
(
  'Avocado Toast',
  'Breakfast',
  'https://www.allrecipes.com/thmb/mJJPeaKKj61DZ4kc_jHHVI3kmG8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/AvocadoToastwithEggFranceC4x3-bb87e3bbf1944657b7db35f1383fabdb.jpg',
  'Creamy avocado spread on toasted bread.',
  ARRAY['Avocado', 'Bread', 'Salt', 'Pepper', 'Lemon Juice'],
  'Mash avocado, spread on toast, season to taste.',
  1,
  4.3,
  10
),
(
  'Oatmeal with Fruits',
  'Breakfast',
  'https://www.pcrm.org/sites/default/files/Oatmeal%20and%20Berries.jpg',
  'Warm oatmeal topped with fresh fruits.',
  ARRAY['Oats', 'Water', 'Banana', 'Berries', 'Honey'],
  'Cook oats, top with sliced fruits and honey.',
  2,
  5.0,
  15
),
(
  'Smoothie Bowl',
  'Breakfast',
  'https://minimalistbaker.com/wp-content/uploads/2016/07/The-PERFECT-5-minute-Smoothie-Bowl-Simple-ingredients-naturally-sweet-SO-healthy-vegan-glutenfree-smoothiebowl-recipe.jpg',
  'A refreshing smoothie topped with fruits and nuts.',
  ARRAY['Banana', 'Spinach', 'Almond Milk', 'Granola'],
  'Blend ingredients, pour into a bowl, and top.',
  1,
  4.7,
  10
),
(
  'Eggs Benedict',
  'Breakfast',
  'https://www.jocooks.com/wp-content/uploads/2020/08/eggs-benedict-1-13.jpg',
  'Poached eggs on English muffins with hollandaise.',
  ARRAY['Eggs', 'English Muffins', 'Ham', 'Hollandaise Sauce'],
  'Poach eggs, assemble on muffins, drizzle sauce.',
  2,
  4.5,
  20
),
(
  'Caesar Salad',
  'Lunch',
  'https://bakerbynature.com/wp-content/uploads/2025/01/Caesar-Salad-9.jpg',
  'A fresh salad with romaine lettuce and Caesar dressing.',
  ARRAY['Romaine Lettuce', 'Croutons', 'Parmesan Cheese', 'Caesar Dressing'],
  'Toss ingredients together and serve chilled.',
  2,
  4.7,
  15
),
(
  'Turkey Sandwich',
  'Lunch',
  'https://www.seriouseats.com/thmb/97w7oMXdTDMWCCuuDoGqiz5Rmv0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/20191010-leftover-turkey-reuben-sandwich-vicky-wasik-hero-a7f18588174f4a789d3430abf814ca38.jpg',
  'A hearty sandwich with turkey and veggies.',
  ARRAY['Turkey', 'Bread', 'Lettuce', 'Tomato', 'Mayonnaise'],
  'Layer ingredients between slices of bread.',
  1,
  4.0,
  10
),
(
  'Quinoa Bowl',
  'Lunch',
  'https://images.themodernproper.com/production/posts/2020/QuinoaBowl_4.jpg?w=800&q=82&auto=format&fit=crop&dm=1737605526&s=c617498b670834babd96fbdcd128e1b4',
  'Nutritious quinoa bowl with vegetables and dressing.',
  ARRAY['Quinoa', 'Chickpeas', 'Cucumber', 'Feta', 'Olive Oil'],
  'Cook quinoa, mix with other ingredients, drizzle dressing.',
  2,
  3.8,
  30
),
(
  'Tomato Soup',
  'Lunch',
  'https://www.allrecipes.com/thmb/qAepi_kEfeNzEjm4TtdMDHMeHnE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/277311spicy-fresh-tomato-soupFranceC4x3-56454ad082214f33960f62665fc8c169.jpg',
  'Warm, comforting tomato soup served with bread.',
  ARRAY['Tomatoes', 'Onion', 'Garlic', 'Basil', 'Cream'],
  'Cook tomatoes and veggies, blend until smooth.',
  4,
  4.1,
  25
),
(
  'Sushi Rolls',
  'Lunch',
  'https://www.allrecipes.com/thmb/P0zUzOzkJGTm9iDvMnzdZ1ua_T8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/19511smoked-salmon-sushi-rollfabeveryday4x3-159a22b4d3ac49fe9a146db94b53c930.jpg',
  'Delicious sushi rolls with fresh ingredients.',
  ARRAY['Sushi Rice', 'Nori', 'Fish', 'Vegetables', 'Soy Sauce'],
  'Roll ingredients in nori and slice.',
  6,
  5.0,
  40
),
(
  'Spaghetti Carbonara',
  'Dinner',
  'https://www.allrecipes.com/thmb/CKRPG_da4wLz3j0pYv0e2jDdF6A=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/4499842-257380-AR-spaghetti-alla-carbonara-tradizionali-buckwheat-queen-4x3-eb4e48956fbd4277adcc3556e3bf6ecc.jpg',
  'A classic Italian pasta dish with a creamy sauce.',
  ARRAY['Spaghetti', 'Eggs', 'Parmesan Cheese', 'Pancetta', 'Black Pepper'],
  'Cook pasta, mix with eggs and cheese, add pancetta.',
  4,
  4.6,
  30
),
(
  'Grilled Salmon',
  'Dinner',
  'https://www.allrecipes.com/thmb/S9CtWJQki8yNesfmTPt8tCDl6uo=/0x512/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/ALR-12720-grilled-salmon-i-VAT-4x3-888cac0fb8a34f6fbde7bf836850cd1c.jpg',
  'Perfectly grilled salmon served with vegetables.',
  ARRAY['Salmon', 'Olive Oil', 'Lemon', 'Herbs', 'Salt'],
  'Marinate salmon, grill until cooked through.',
  2,
  4.4,
  25
),
(
  'Beef Stir-Fry',
  'Dinner',
  'https://www.allrecipes.com/thmb/InZbAAssBhhPBPPqVhexfaK6sA8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/M7014953_JD_11856-4x3-1-0d0cefed5bea4c4ba04bee3ff63c439a.jpg',
  'Quick and flavorful beef stir-fry with vegetables.',
  ARRAY['Beef', 'Bell Peppers', 'Broccoli', 'Soy Sauce', 'Garlic'],
  'Stir-fry beef and veggies in a hot pan.',
  4,
  4.3,
  20
),
(
  'Vegetable Curry',
  'Dinner',
  'https://www.allrecipes.com/thmb/djEkHAUHBflfrzoCLPeAbn0a0oc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/13982-quick-and-easy-vegetable-curry-VAT-001-4x3-6a77fe207b71496da15bee83b5db22f9.jpg',
  'A rich and aromatic vegetable curry.',
  ARRAY['Mixed Vegetables', 'Coconut Milk', 'Curry Paste', 'Rice'],
  'Cook vegetables in coconut milk with curry paste.',
  4,
  5.0,
  35
),
(
  'Chicken Tacos',
  'Dinner',
  'https://www.allrecipes.com/thmb/nEXud4i-ZmJQmW2B_X4BDay06ZI=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/217890-ranch-chicken-tacos-VAT-001-4x3-26519e4dc43242b0b5c4ae09178511c5.jpg',
  'Flavorful chicken tacos topped with fresh ingredients.',
  ARRAY['Chicken', 'Taco Shells', 'Lettuce', 'Tomato', 'Cheese'],
  'Cook chicken, fill taco shells, and top as desired.',
  3,
  4.2,
  15
),
(
  'Spaghetti Aglio e Olio',
  'Dinner',
  'https://www.allrecipes.com/thmb/s6u_2dpgcuj32sjyKJTzHUpXFk0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8829154-42004bab5a0343579fbae2b77a6af065.jpg',
  'Simple Italian pasta dish.',
  ARRAY['Spaghetti', 'Garlic', 'Olive Oil', 'Chili Flakes'],
  'Cook pasta, sauté garlic, mix together.',
  4,
  4.8,
  20
),
(
  'Garlic Butter Shrimp',
  'Dinner',
  'https://www.allrecipes.com/thmb/PYlStsLc33QunInprsqhqMZArU8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8707636-garlic-butter-shrimp-jojamada-4x3-1-276e02bf5b884c04b1bedb6e57e4d4bf.jpg',
  'Succulent shrimp tossed in garlic butter and herbs.',
  ARRAY['Shrimp', 'Garlic', 'Butter', 'Parsley', 'Lemon'],
  'Sauté garlic in butter, add shrimp until pink, finish with lemon and parsley.',
  2,
  4.7,
  15
),
(
  'Chicken Alfredo Pasta',
  'Dinner',
  'https://www.allrecipes.com/thmb/L6XHFLKIpyzz2iIJRRRKztpFyT8=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/9203140-9ef5315609dc4c3bbbdfc0c539bf2c37.jpg',
  'Creamy Alfredo pasta with grilled chicken.',
  ARRAY['Pasta', 'Chicken Breast', 'Cream', 'Parmesan', 'Garlic'],
  'Cook pasta; grill chicken; make sauce with cream, garlic, parmesan; combine.',
  4,
  4.6,
  30
),
(
  'Beef Tacos',
  'Dinner',
  'https://www.allrecipes.com/thmb/0af4bstQ_7L_5-3WersLJb1V5A4=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/5507683-d90260ef71a44e3988219f46e6d70591.jpg',
  'Spiced ground beef in soft tortillas with toppings.',
  ARRAY['Ground Beef', 'Taco Seasoning', 'Tortillas', 'Lettuce', 'Cheddar'],
  'Cook beef with seasoning; warm tortillas; assemble with toppings.',
  4,
  4.5,
  20
),
(
  'Vegetable Stir Fry',
  'Dinner',
  'https://www.allrecipes.com/thmb/RbLgplpltHlYKvYRd79vSzKvpbw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/987394-efe9cc2da3e843cbb82c5798daeebffc.jpg',
  'Colorful mixed vegetables in a savory stir-fry sauce.',
  ARRAY['Broccoli', 'Bell Pepper', 'Carrot', 'Soy Sauce', 'Garlic'],
  'Stir-fry vegetables on high heat; add sauce; cook until crisp-tender.',
  3,
  4.3,
  15
),
(
  'Salmon with Lemon Dill',
  'Dinner',
  'https://www.allrecipes.com/thmb/STYFM6TeywhEFliPi0_yHWoIwfM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/6637559-cedar-plank-grilled-salmon-with-garlic-lemon-and-dill-Mackenzie-Schieck-4x3-1-aa9c00cd2c20464aa76e87f4d9cc6336.jpg',
  'Oven-baked salmon with lemon and fresh dill.',
  ARRAY['Salmon Fillets', 'Lemon', 'Dill', 'Olive Oil', 'Salt'],
  'Season salmon, bake until flaky, finish with lemon and dill.',
  2,
  4.8,
  18
),
(
  'Eggplant Parmesan',
  'Dinner',
  'https://www.allrecipes.com/thmb/SYLFQEdUs77haviXqVKPstPfex4=/0x512/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/25321-eggplant-parmesan-ii-DDMFS-4x3-6d53ce79765b4c3d9f554d2a47e14d00.jpg',
  'Baked breaded eggplant layered with marinara and cheese.',
  ARRAY['Eggplant', 'Breadcrumbs', 'Marinara', 'Mozzarella', 'Parmesan'],
  'Bread and bake eggplant slices; layer with sauce and cheese; bake until bubbly.',
  4,
  4.4,
  50
),
(
  'Chicken Curry',
  'Dinner',
  'https://www.allrecipes.com/thmb/o9Cs2KkpzW7FXLAhEjLItDNrBzY=/0x512/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/46822-Indian-Chicken-Curry-PICS-Beauty-4x3-9535b806e7dc4f1da14f8ddb7a6367a4.jpg',
  'Comforting chicken curry with warm spices.',
  ARRAY['Chicken', 'Onion', 'Tomato', 'Curry Powder', 'Coconut Milk'],
  'Sauté aromatics, add spices, chicken and tomatoes; simmer with coconut milk.',
  4,
  4.6,
  40
),
(
  'Margherita Pizza',
  'Dinner',
  'https://www.allrecipes.com/thmb/w4qiT98TMy_bUouM5hkz0-IhPXs=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/PuffPastryMargheritaPizzafabeveryday-5ed9c908f84441e8b5cd3f0425ecef0d.jpg',
  'Classic pizza with tomato, basil, and mozzarella.',
  ARRAY['Pizza Dough', 'Tomato Sauce', 'Mozzarella', 'Basil', 'Olive Oil'],
  'Stretch dough, add sauce and cheese, bake until crust is golden; top with basil.',
  3,
  4.7,
  20
),
(
  'Beef Stroganoff',
  'Dinner',
  'https://www.allrecipes.com/thmb/wy6uuIhE7wHNwHNcvgd0bBZF4KM=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/475838-639b6d9a460c4a5da1b3e1396a97ff13.jpg',
  'Creamy beef and mushroom sauce served over noodles.',
  ARRAY['Beef Strips', 'Mushrooms', 'Onion', 'Sour Cream', 'Egg Noodles'],
  'Sear beef, sauté mushrooms and onion, add sauce and sour cream; serve over noodles.',
  4,
  4.5,
  35
),
(
  'Stuffed Bell Peppers',
  'Dinner',
  'https://www.allrecipes.com/thmb/4Wse8o-YIFvkjyVfrNFPtLvPsIc=/0x512/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/AR-236359-beef-and-rice-stuffed-bell-peppers-DDMFS-4x3-beauty-dd9458de98884d4eb362354ee626d70e.jpg',
  'Bell peppers filled with rice, meat and cheese, baked to perfection.',
  ARRAY['Bell Peppers', 'Ground Beef', 'Rice', 'Tomato Sauce', 'Cheddar'],
  'Mix cooked rice and beef with sauce; fill peppers; top with cheese and bake.',
  6,
  4.4,
  60
),
(
  'Lemon Herb Chicken',
  'Dinner',
  'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2022%2F01%2F26%2FSimple-Lemon-Herb-Chicken-2000.jpg&q=60&c=sc&poi=auto&orient=true&h=512',
  'Roasted chicken breasts with lemon and herbs.',
  ARRAY['Chicken Breast', 'Lemon', 'Rosemary', 'Olive Oil', 'Garlic'],
  'Marinate chicken, roast until cooked through, serve with pan juices.',
  4,
  4.6,
  30
),
(
  'Shrimp Paella',
  'Dinner',
  'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2021%2F11%2F04%2Fimage-460.jpg&q=60&c=sc&poi=auto&orient=true&h=512',
  'Spanish rice with shrimp, saffron and vegetables.',
  ARRAY['Rice', 'Shrimp', 'Saffron', 'Bell Pepper', 'Peas'],
  'Sauté ingredients, add rice and stock with saffron, simmer until rice is done.',
  4,
  4.7,
  40
),
(
  'Pork Chops with Apples',
  'Dinner',
  'https://www.allrecipes.com/thmb/Ea7N1TLk4neLGBEcgJFTRzFG55A=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/4570368-applesauce-pork-chops-Gary-Lee-Gillmeister-4x3-1-38244a0ed7684dc396b8396f6aaa08cc.jpg',
  'Pan-seared pork chops with caramelized apples and onions.',
  ARRAY['Pork Chops', 'Apple', 'Onion', 'Butter', 'Thyme'],
  'Sear chops, sauté apples and onions in butter, combine and finish cooking.',
  4,
  4.3,
  25
),
(
  'Mushroom Risotto',
  'Dinner',
  'https://www.allrecipes.com/thmb/jS8MN9Wqt63jmihoTQ7yLc497M4=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/9416606-74723cfc8c8b4e378d804b292b598649.jpg',
  'Creamy arborio rice with sautéed mushrooms and parmesan.',
  ARRAY['Arborio Rice', 'Mushrooms', 'Parmesan', 'Onion', 'White Wine'],
  'Toast rice, gradually add stock stirring constantly, finish with mushrooms and parmesan.',
  4,
  4.6,
  35
),
(
  'Beef Bourguignon',
  'Dinner',
  'https://www.allrecipes.com/thmb/HKRuYbWzT5L1g-dGbQ28_q3fL1o=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Easy-Beef-Bourguignon-France-C-1x1-1-2000-d5cfe1fd2624463e9832662e9a004c7d.jpg',
  'Classic French beef stew braised in red wine.',
  ARRAY['Beef Chuck', 'Red Wine', 'Carrot', 'Onion', 'Mushroom'],
  'Brown beef, add wine and stock, simmer with vegetables until tender.',
  6,
  4.8,
  180
),
(
  'Chicken Fajitas',
  'Dinner',
  'https://www.allrecipes.com/thmb/UNZMCXRd1KMETWzWqlT8qL6MeIk=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/1005429-karens-slow-cooker-chicken-fajitas-Trusted-Brands-1x1-1-9408e6ffa66f408ebfff70c56c60c987.jpg',
  'Sizzling chicken strips with peppers and onions for fajitas.',
  ARRAY['Chicken', 'Bell Peppers', 'Onion', 'Tortillas', 'Fajita Seasoning'],
  'Sauté chicken and vegetables with seasoning; serve with warm tortillas.',
  4,
  4.5,
  20
),
(
  'Lentil Soup',
  'Dinner',
  'https://www.allrecipes.com/thmb/_bvtK6VQb8rV4whUErtdntFUOHs=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/13978-lentil-soup-DDMFS-4x3-edfa47fc6b234e6b8add24d44c036d43.jpg',
  'Hearty lentil soup with vegetables and herbs.',
  ARRAY['Lentils', 'Carrot', 'Celery', 'Onion', 'Vegetable Stock'],
  'Sauté vegetables, add lentils and stock, simmer until lentils are tender.',
  6,
  4.4,
  45
),
(
  'Teriyaki Salmon Bowl',
  'Dinner',
  'https://www.allrecipes.com/thmb/cV1gx2Pv4LQd3_Z7jtF0JpdEhKM=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/11871553_5-Ingrediuent-Salmon-Teriyaki-Bowls_Peyton-Beckwith_4x3-6eebd27af072474f9b2c2f49d6edf32c.jpg',
  'Glazed salmon served over rice with vegetables.',
  ARRAY['Salmon', 'Teriyaki Sauce', 'Rice', 'Broccoli', 'Sesame Seeds'],
  'Glaze salmon with teriyaki, bake or pan-sear; serve over rice with veggies.',
  2,
  4.7,
  25
),
(
  'Gnocchi with Pesto',
  'Dinner',
  'https://www.allrecipes.com/thmb/38YYoAdB6PMKYRoBQ5-4BP3SWPg=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/230326gnocchi-with-chicken-pesto-and-fresh-mozzarellaMyHotSouthernMEss4x3-c649f7aa19594eeaa10530ae688ff25b.jpg',
  'Potato gnocchi tossed in fresh basil pesto and cherry tomatoes.',
  ARRAY['Gnocchi', 'Basil', 'Pine Nuts', 'Parmesan', 'Cherry Tomatoes'],
  'Cook gnocchi, toss with pesto and tomatoes, serve warm.',
  3,
  4.4,
  15
),
(
  'BBQ Pulled Pork Sandwiches',
  'Dinner',
  'https://www.allrecipes.com/thmb/jkgY77k3lKZSUEoxZ6CPlOwia0g=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/2077235-19269344fce84242b4b76bc8e9cea73a.jpg',
  'Slow-cooked pulled pork tossed in BBQ sauce on buns.',
  ARRAY['Pork Shoulder', 'BBQ Sauce', 'Buns', 'Coleslaw', 'Onion'],
  'Slow cook pork until tender, shred, mix with BBQ sauce, serve on buns with slaw.',
  8,
  4.6,
  480
),
(
  'Thai Green Curry',
  'Dinner',
  'https://www.allrecipes.com/thmb/trbEa6VCDJ7lg_3SI9W7GNcKwcY=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/282096-instant-pot-thai-style-green-curry-chicken-3d431b4b188f4ba990b57d75f44942e3.jpg',
  'Fragrant green curry with vegetables and choice of protein.',
  ARRAY['Green Curry Paste', 'Coconut Milk', 'Chicken', 'Bamboo Shoots', 'Basil'],
  'Simmer curry paste in coconut milk, add chicken and vegetables, finish with basil.',
  4,
  4.6,
  30
),
(
  'Spinach and Feta Stuffed Chicken',
  'Dinner',
  'https://www.allrecipes.com/thmb/THf_cUCTwxGq1knutMHGSdLesPI=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8653824-feta-spinach-stuffed-chicken-breasts-ddmfs-hero-4x3-42432-cfa7ced044aa4f3d8eb860a3a451cee8.jpg',
  'Juicy chicken breast stuffed with spinach and feta cheese.',
  ARRAY['Chicken Breast', 'Spinach', 'Feta', 'Garlic', 'Olive Oil'],
  'Stuff chicken with spinach and feta, secure and bake until cooked through.',
  4,
  4.5,
  35
),
(
  'Shrimp Scampi Linguine',
  'Dinner',
  'https://www.allrecipes.com/thmb/OSeHp5Si1XLqSkRHkat9d24hBpg=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/6064240-0129e7ef59894373b14b604cad3e0b18.jpg',
  'Garlicky shrimp tossed with linguine in lemon-butter sauce.',
  ARRAY['Shrimp', 'Linguine', 'Garlic', 'Butter', 'Lemon'],
  'Sauté garlic in butter, cook shrimp briefly, toss with pasta and lemon.',
  4,
  4.7,
  20
),
(
  'Baked Ziti',
  'Dinner',
  'https://www.allrecipes.com/thmb/a3-nk6kH6_SeeEKATjw4A0kPbgQ=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/AR-JF-11758-Baked-Ziti-ddmfs-3x4-0630757a10b1492e85daab40662225b3.jpg',
  'Pasta baked with ricotta, tomato sauce and melted mozzarella.',
  ARRAY['Ziti', 'Ricotta', 'Tomato Sauce', 'Mozzarella', 'Parmesan'],
  'Mix pasta with ricotta and sauce, top with mozzarella, bake until bubbly.',
  6,
  4.5,
  40
),
(
  'Seared Tuna Steak',
  'Dinner',
  'https://www.allrecipes.com/thmb/MrACYlrnSsSmKs-z3UH6sfQigL4=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/160099-seared-ahi-tuna-steaks-DDMFS-4x3-26f4691e91bd434e9d96c1c601608cbc.jpg',
  'Quick seared tuna with sesame crust and soy dipping sauce.',
  ARRAY['Tuna Steak', 'Sesame Seeds', 'Soy Sauce', 'Ginger', 'Lime'],
  'Coat tuna with sesame, sear briefly each side, serve with soy-ginger sauce.',
  2,
  4.6,
  10
),
(
  'Creamy Tomato Basil Soup',
  'Dinner',
  NULL,
  'Smooth tomato soup finished with cream and fresh basil.',
  ARRAY['Tomatoes', 'Onion', 'Garlic', 'Cream', 'Basil'],
  'Cook tomatoes with aromatics, blend until smooth, finish with cream and basil.',
  4,
  4.3,
  35
),
(
  'Vegetarian Chili',
  'Dinner',
  'https://www.allrecipes.com/thmb/jEWoP9Aj_RIPC_wSuB76_av_6-0=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/6281236-insanely-easy-vegetarian-chili-Ellyx3-1x1-1-d3b032efeb244cdc9b07c21a1f7943bb.jpg',
  'Hearty chili with beans, vegetables and spices.',
  ARRAY['Beans', 'Tomato', 'Bell Pepper', 'Onion', 'Chili Powder'],
  'Sauté vegetables, add beans and tomatoes, simmer with spices until flavors meld.',
  6,
  4.4,
  60
),
(
  'Steak with Chimichurri',
  'Dinner',
  'https://www.allrecipes.com/thmb/415ErxS1JKZ_752BPcV4Svr_w4E=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/3457367-b0264a5d3d3d480490a3921ea72f9157.jpg',
  'Grilled steak served with vibrant chimichurri sauce.',
  ARRAY['Steak', 'Parsley', 'Garlic', 'Olive Oil', 'Red Wine Vinegar'],
  'Grill steak to desired doneness; blend chimichurri ingredients and spoon over steak.',
  2,
  4.8,
  20
),
(
  'Butternut Squash Pasta',
  'Dinner',
  'https://www.allrecipes.com/thmb/ID97BJ8_Gta9otEhBKzz8xmbaH8=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/710152-728c3d5dc24649fcb65155381f7c59f7.jpg',
  'Roasted squash blended into a creamy pasta sauce with sage.',
  ARRAY['Butternut Squash', 'Pasta', 'Sage', 'Parmesan', 'Cream'],
  'Roast squash, blend into sauce, toss with pasta and garnish with sage and parmesan.',
  4,
  4.5,
  40
),
(
  'Fish Tacos',
  'Dinner',
  'https://www.allrecipes.com/thmb/ov4ijlOz9P9ogjtVL-dTWH5uimk=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/5390580-0953affd3c8b42c0aea28254dcbf72dd.jpg',
  'Crisp-fried or grilled fish in tortillas with slaw and lime.',
  ARRAY['White Fish', 'Tortillas', 'Cabbage', 'Lime', 'Sour Cream'],
  'Cook fish, warm tortillas, assemble with slaw, crema and lime.',
  4,
  4.6,
  25
),
(
  'Ratatouille',
  'Dinner',
  'https://www.allrecipes.com/thmb/PkW1sTYjqFy3NqU6DIPG-Ot2_0k=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/222006-disneys-ratatouille-DDMFS-4x3-36eb15843ab548a79e7aab761dac92e1.jpg',
  'Layered baked vegetables in a savory tomato base.',
  ARRAY['Zucchini', 'Eggplant', 'Tomato', 'Bell Pepper', 'Herbs de Provence'],
  'Sauté base sauce, layer sliced vegetables, bake until tender.',
  4,
  4.2,
  60
),
(
  'Korean Beef Bibimbap',
  'Dinner',
  'https://www.allrecipes.com/thmb/Ek7F_I3DXkxRUhijF8_74rOiVnc=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/228240-BibimbapKoreanRiceWithMixedVegtables-ddmfs-1X1-0668-4a27ecc75afd40c78baa24e4e75d65a6.jpg',
  'Mixed rice bowl with seasoned beef, vegetables and gochujang sauce.',
  ARRAY['Rice', 'Ground Beef', 'Spinach', 'Carrot', 'Gochujang'],
  'Cook rice; sauté beef with seasoning; assemble with vegetables and sauce; top with fried egg.',
  4,
  4.7,
  30
),
(
  'Chicken Marsala',
  'Dinner',
  'https://www.allrecipes.com/thmb/zNNDv5g6-eMcw4sH8Y3WAy4ePLk=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/5694215-easier-chicken-marsala-Allison-Volosin-4x3-1-bbd980b9d0a843ba9248613448c9d62f.jpg',
  'Pan-fried chicken cutlets with marsala wine and mushrooms.',
  ARRAY['Chicken Cutlets', 'Marsala Wine', 'Mushrooms', 'Butter', 'Flour'],
  'Dredge and sauté chicken, add mushrooms and marsala sauce; reduce and serve.',
  4,
  4.5,
  30
),
(
  'Cajun Jambalaya',
  'Dinner',
  'https://www.allrecipes.com/thmb/cPHoaTbKmhpI_h8Ax3dXOEV8EO4=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/1448054-a87a23fb37984168873153cf96fbb37a.jpg',
  'Spicy rice dish with sausage, chicken and shrimp.',
  ARRAY['Rice', 'Andouille Sausage', 'Chicken', 'Shrimp', 'Cajun Seasoning'],
  'Sauté ingredients, add rice and stock, simmer until rice absorbs flavors.',
  6,
  4.6,
  50
),
(
  'Greek Moussaka',
  'Dinner',
  'https://www.allrecipes.com/thmb/VYlqph8Apang_oxNWFq3KTA7BZc=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/19644-moussaka-DDMFS-4x3-066ed4bc6ee14583a81e276020bb4ea7.jpg',
  'Layered eggplant and spiced meat topped with béchamel.',
  ARRAY['Eggplant', 'Ground Lamb', 'Tomato', 'Béchamel', 'Onion'],
  'Layer cooked eggplant and meat sauce, top with béchamel and bake until set.',
  8,
  4.5,
  90
),
(
  'Spaghetti Carbonara',
  'Dinner',
  'https://www.allrecipes.com/thmb/lhLxw6rwEMT1crUHXmm5edrwjA8=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/245775-spaghetti-alla-carbonara-the-traditional-italian-recipe-DDMFS-4x3-879c32ee3cfb463582e3e6230e311029.jpg',
  'Classic carbonara with eggs, pancetta and pecorino.',
  ARRAY['Spaghetti', 'Eggs', 'Pancetta', 'Pecorino', 'Black Pepper'],
  'Cook pasta; mix eggs and cheese; toss hot pasta with pancetta and egg mixture off heat.',
  4,
  4.7,
  20
),
(
  'Chicken Piccata',
  'Dinner',
  'https://www.allrecipes.com/thmb/zrVggtbsm__lkbXoQGWdwfYmYe8=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8696288-chicken-piccata-meatballs-recipe-Allrecipes-Magzine-JF_ALRSP25_4x3-47dca6e6b5814a27bc16be19adb16ca5.jpg',
  'Light chicken in lemon-caper sauce.',
  ARRAY['Chicken Breast', 'Capers', 'Lemon', 'Butter', 'Flour'],
  'Pan-fry chicken, deglaze with lemon and stock, add capers and butter to finish.',
  4,
  4.5,
  25
),
(
  'Vegetable Lasagna',
  'Dinner',
  'https://www.allrecipes.com/thmb/XcxViM4UZeI7ZES68fxjiFmOPho=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/620560-8ffeed667b4144d3acd4b9e63d07c013.jpg',
  'Layered lasagna with roasted vegetables and cheese.',
  ARRAY['Lasagna Noodles', 'Zucchini', 'Spinach', 'Ricotta', 'Tomato Sauce'],
  'Assemble layers of noodles, vegetables, cheese and sauce; bake until bubbly.',
  8,
  4.4,
  60
),
(
  'Sausage and Peppers',
  'Dinner',
  'https://www.allrecipes.com/thmb/nEbW8dhrOnLxaNSORvu7hakKaDE=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/214500-sausage-peppers-onions-and-potato-bake-DDMFS-4x3-16e08956570d42578c49791529430d08.jpg',
  'Italian sausages simmered with peppers and onions in tomato sauce.',
  ARRAY['Italian Sausage', 'Bell Peppers', 'Onion', 'Tomato Sauce', 'Garlic'],
  'Brown sausages, sauté peppers and onions, combine with sauce and simmer.',
  4,
  4.3,
  30
),
(
  'Coconut Chickpea Curry',
  'Dinner',
  'https://www.allrecipes.com/thmb/VQjCXqH_01CQanJCyRPJRJdfnX8=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/Coconut_Chickpea_Curry-4x3_039-cfa7a55e16434fba8641012f7b03cef8.jpg',
  'Creamy chickpea curry with coconut milk and spices.',
  ARRAY['Chickpeas', 'Coconut Milk', 'Onion', 'Curry Powder', 'Spinach'],
  'Sauté aromatics, add spices, chickpeas and coconut milk; simmer and add spinach.',
  4,
  4.4,
  30
),
(
  'Lamb Kofta',
  'Dinner',
  'https://www.allrecipes.com/thmb/SJs9olMhPlqCi8oGvvAJuxYrgxQ=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8645735_Spiced-Harissa-Beef-and-Lamb-Koftas_Dotdash-Meredith-Food-Studios_4x3-47c377b8eee34191bcda8a17ab3b927e.jpg',
  'Spiced lamb skewers served with yogurt sauce.',
  ARRAY['Ground Lamb', 'Cumin', 'Coriander', 'Garlic', 'Yogurt'],
  'Mix spices with lamb, form skewers, grill and serve with yogurt sauce.',
  4,
  4.6,
  25
),
(
  'Pad Thai',
  'Dinner',
  'https://www.allrecipes.com/thmb/2aHyh25LpKvT0N9Br-0H4hHjJTU=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/42968-pad-thai-DDMFS-4x3-f46b490ef89b4694b8bf4c5ac54a486b.jpg',
  'Stir-fried rice noodles with tamarind sauce, shrimp and peanuts.',
  ARRAY['Rice Noodles', 'Tamarind Paste', 'Shrimp', 'Egg', 'Peanuts'],
  'Soak noodles, stir-fry with sauce, shrimp, egg and garnish with peanuts.',
  4,
  4.7,
  25
),
(
  'Polenta with Mushroom Ragù',
  'Dinner',
  'https://www.allrecipes.com/thmb/8CfurqhEJin3lYkNUa8ZEY21oRM=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/AR-RM-234933-how-to-make-perfect-polenta-ddmfs-3x4-5d4dc27b993a4c4bb33db0e1163dbbba.jpg',
  'Creamy polenta topped with rich mushroom ragù.',
  ARRAY['Polenta', 'Mushrooms', 'Tomato', 'Onion', 'Parmesan'],
  'Cook polenta until creamy; simmer mushrooms in tomato sauce; spoon over polenta.',
  4,
  4.4,
  45
),
(
  'Shrimp and Grits',
  'Dinner',
  'https://www.allrecipes.com/thmb/iKqPEzusJ3xq_vXDDoBwzdqM_3c=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/1296334-e872b13b7f994296a78e0abc76bd3983.jpg',
  'Southern-style shrimp over cheesy grits with bacon.',
  ARRAY['Shrimp', 'Grits', 'Cheddar', 'Bacon', 'Butter'],
  'Cook grits with cheese, sauté shrimp with bacon and butter, serve together.',
  4,
  4.6,
  30
),
(
  'Chicken Enchiladas',
  'Dinner',
  'https://www.allrecipes.com/thmb/vJACQN2yolDHbVy4JCzFQYPnufU=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8691-chicken-enchiladas-DDMFS-4x3-322-de64088bd2e248c7b6f86572e821e9f7.jpg',
  'Shredded chicken rolled in tortillas topped with enchilada sauce and cheese.',
  ARRAY['Chicken', 'Tortillas', 'Enchilada Sauce', 'Cheddar', 'Onion'],
  'Fill tortillas with chicken, roll, top with sauce and cheese, bake until bubbly.',
  6,
  4.5,
  35
),
(
  'Pumpkin Curry',
  'Dinner',
  'https://www.allrecipes.com/thmb/JG2RVVqjFO_CLLEP5yI_TerlsnQ=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/4648542-6243d2b7e2654d129d463d80c760c82a.jpg',
  'Warm spiced pumpkin curry served with rice.',
  ARRAY['Pumpkin', 'Coconut Milk', 'Curry Powder', 'Onion', 'Spinach'],
  'Sauté aromatics, add pumpkin and coconut milk, simmer until tender and season.',
  4,
  4.2,
  35
),
(
  'Ginger Soy Chicken Thighs',
  'Dinner',
  'https://www.allrecipes.com/thmb/U2h66zzKQGxP0Y5OAv08IX4sO8U=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/6388915-478c6715817549378bfab4e272a9b3c6.jpg',
  'Sticky baked chicken thighs glazed with ginger-soy sauce.',
  ARRAY['Chicken Thighs', 'Soy Sauce', 'Ginger', 'Honey', 'Garlic'],
  'Marinate thighs, bake until glazed and cooked through.',
  4,
  4.6,
  40
),
(
  'Calamari Fra Diavolo',
  'Dinner',
  'https://www.allrecipes.com/thmb/bFDes_203bPq_GLihIzrXo_RqCM=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/1378041-calamari-with-tomato-sauce-ypiris-4x3-1-3c6787a7007749bbb53e7dc803f99dfd.jpg',
  'Spicy tomato-based seafood pasta with tender calamari.',
  ARRAY['Calamari', 'Tomato', 'Red Pepper Flakes', 'Garlic', 'Pasta'],
  'Cook sauce with garlic and chili, add calamari and simmer briefly, toss with pasta.',
  4,
  4.3,
  25
),
(
  'Avocado Chicken Salad',
  'Dinner',
  'https://www.allrecipes.com/thmb/0DRzb6OYDJLuKZ7ynD_WGXWWZZ4=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/3709155-09d4fd0a758e47f0b124bd5469ef44b2.jpg',
  'Light chicken salad with creamy avocado and lime dressing.',
  ARRAY['Chicken', 'Avocado', 'Lime', 'Cilantro', 'Red Onion'],
  'Mix shredded chicken with diced avocado and dressing; chill and serve.',
  4,
  4.1,
  15
),
(
  'Oven-Baked Trout Almondine',
  'Dinner',
  'https://www.beyondthechickencoop.com/wp-content/uploads/2022/11/Trout-Almondine.jpg',
  'Delicate trout baked with buttery almonds and lemon.',
  ARRAY['Trout', 'Almonds', 'Butter', 'Lemon', 'Parsley'],
  'Top trout with almonds and butter, bake until flaky, finish with lemon and parsley.',
  2,
  4.5,
  20
),
(
  'Mango Chicken Stir Fry',
  'Dinner',
  'https://www.allrecipes.com/thmb/6zs526myOl2zBhz-ll11RwB8hsM=/282x188/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8527054-Mango-Chicken-Stir-Fry-Bibi8527057-1x1-1-6f6a16007da64afba20ce0c42d1e2a94.jpg',
  'Sweet and savory stir-fry with mango and chicken.',
  ARRAY['Chicken', 'Mango', 'Bell Pepper', 'Soy Sauce', 'Ginger'],
  'Stir-fry chicken and vegetables, add mango and sauce, cook until glazed.',
  4,
  4.3,
  20
);
